# In order to use docker for development we use version 2 to install dependencies
# A less than optimal solution would be to inclue command: bash -c "npm install && npm run dev"
# ##########  INTSTRUCTIONS ##############
# From the command line, to install the versions of binaries needed run the following:
# docker-compose -f docker-compose.builder.yml run --rm install
# Other commands are run with a change at the end:
# docker-compose -f docker-compose.builder.yml run --rm build
# These are all in the Makefile for easy access
version: '2'
services:
  base:
    # base image
    image: node:10.18
    # If we are using this for development, when our local files change, the files in the container also need to change "." local : mounted
    # we will mount our current directory to /usr/src/service in the container
    # And allow the node_modules to live on its own with an external volume
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
  # our package dependencies
  install:
    extends:
      service: base
    command: npm i
  # TODO: what if we wanted to add more dependencies?
  # Other commands, for example, build bundle with webpack, see package.json
  build:
    extends:
      service: base
    command: npm run dev:build
volumes:
  nodemodules:
    external: true