version: '3.2'
services:
  chart:
    image: bellcd/robinhood:price-chart
    depends_on:
      - mongo
    ports:
      - '4444:4444'
    links:
      - "mongo:db"
      - "mongo:database"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    ports:
      - '1000:27017'