version: '3'
services:
  chart:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app
    # image: bellcd/robinhood:chart
    depends_on:
      - mongo
    ports:
      - '4444:4444'
    links:
      - "mongo:db"
      - "mongo:database"
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    ports:
      - '1000:27017'