# TODO: It's not executing both commands in the container ...
# Execute this file once once docker is installed
docker-compose up
# TODO: workaround because docker-compose doesn't seem to be executing multiple shell commands in one line ...
docker exec chart_chart_1 node server/server.js